version: '3.7'

services:
  db:
    image: postgres:11
    container_name: 'gobarber-db'
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - './.docker/database/data:/var/lib/postgresql/data'
    ports:
      - 5432:5432

  mongodb:
    image: mongo:latest
    container_name: "gobarber-mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./.docker/mongo/data:/data/db
    ports:
      - 27017:27017
