version: '3.7'

services:

  app:
    build: .
    container_name: gobarber-app
    # entrypoint: /var/www/.docker/app/entrypoint.sh
    ports:
      - "3333:3333"
    volumes:
      - .:/var/www
    depends_on:
      - db
      - mongodb
      - redis
    networks:
      - app-network

  db:
    image: postgres:11
    container_name: 'gobarber-db'
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - './.docker/database/data:/var/lib/postgresql/data'
    ports:
      - 5432:5432
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: "gobarber-mongodb"
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./.docker/mongo/data:/data/db
    ports:
      - 27017:27017
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: gobarber-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./.docker/redis:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
